# Whether to create the namespace or rely on --namespace
createNamespace: false
namespace: default

appName: react-app
serviceName: react-app

replicaCount: 3
revisionHistoryLimit: 2

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

image:
  repository: jordansuber/my-react-app
  tag: "0.0.2"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000
  targetPort: 3000
  externalTrafficPolicy: Cluster
  annotations: {}
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  sessionAffinity: None
  loadBalancerSourceRanges: []

# Optional ConfigMap mount
configMap:
  enabled: false
  name: ""
  mountPath: "/etc/config"

# Optional Secret mount
secret:
  enabled: false
  name: ""
  mountPath: "/etc/secret"

nodeSelector: {}
tolerations: []
affinity: {}

readinessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /
    port: 3000
  initialDelaySeconds: 30
  periodSeconds: 30

ingress:
  enabled: true
  ingressClassName: alb
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    # alb.ingress.kubernetes.io/subnets: "subnet-0bb1c79de3ac67c8b,subnet-064f7f4b8a9b0cde1"
    # alb.ingress.kubernetes.io/security-groups: "sg-0f8e9d7c6b5a43210"
    # alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
  hosts:
      paths:
        - path: /
          pathType: Prefix
  tls: []
