# Whether to create the namespace or rely on --namespace
createNamespace: false
namespace: default

appName: react-app
serviceName: react-app

replicaCount: 3

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

image:
  repository: 866934333672.dkr.ecr.us-east-1.amazonaws.com/jordansuber/react-app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000
  targetPort: 3000
  externalTrafficPolicy: Cluster
  annotations: {}
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  sessionAffinity: None
  loadBalancerSourceRanges: []

ingress:
  enabled: true
  ingressClassName: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
  hosts:
    - host: react.mycompany.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

nodeSelector: {}
tolerations: []
affinity: {}

# Optional ConfigMap/Secret injection
configMap:
  enabled: false
  name: ""
  data: {}

secret:
  enabled: false
  name: ""
  data: {}

# For private registries
imagePullSecrets: []
