apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "react-app.fullname" . }}
  labels:
    {{- include "react-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "react-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "react-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          envFrom:
            {{- if and .Values.configMap.enabled .Values.configMap.name }}
            - configMapRef:
                name: {{ .Values.configMap.name }}
            {{- end }}
            {{- if and .Values.secret.enabled .Values.secret.name }}
            - secretRef:
                name: {{ .Values.secret.name }}
            {{- end }}
