apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    {{ include "react-app.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  selector:
    {{ include "react-app.selectorLabels" . | nindent 4 }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      protocol: {{ default "TCP" .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
