name: Build & Deploy to S3

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install & Build
        working-directory: app
        run: |
          npm ci
          npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::866934333672:role/YourDeployRole

      - name: Sync to S3
        run: |
          BUCKET=$(terraform -chdir=environments/dev output -raw assets_bucket_name)
          aws s3 sync app/dist/ s3://$BUCKET/ \
            --delete \
            --acl bucket-owner-full-control

      - name: Invalidate CloudFront (optional)
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} \
            --paths "/*"
